site_name: ${{values.componentName}}-${{values.serviceName}}
site_description: 'Main documentation for ${{values.componentName}}-${{values.serviceName}}'
repo_url: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Getting Started:
      - Getting Started: 'docs/index.md'
